apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "testcluster-a693"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "testcluster-a693"
    spec:
      containers:
        - name: "testcluster-a693"
          image: "fhlkube.azurecr.io/testcluster"
          ports:
          - containerPort: 80