apiVersion: v1
kind: Service
metadata:
    name: "testcluster-a693"
    labels:
        app: "testcluster-a693"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testcluster-a693"