apiVersion: v1
kind: Service
metadata:
    name: "testcluster-c321"
    labels:
        app: "testcluster-c321"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testcluster-c321"