on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fhlkube.azurecr.io
        username: ${{ secrets.acr_fhlkube_username }}
        password: ${{ secrets.acr_fhlkube_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t fhlkube.azurecr.io/testcluster:${{ github.sha }}
        docker push fhlkube.azurecr.io/testcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testcluster4db5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testcluster4db5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testcluster4db5
        container-registry-url: fhlkube.azurecr.io
        container-registry-username: ${{ secrets.acr_fhlkube_username }}
        container-registry-password: ${{ secrets.acr_fhlkube_password }}
        secret-name: testclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: testcluster4db5
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          fhlkube.azurecr.io/testcluster:${{ github.sha }}
        imagepullsecrets: |
          testclusterdockerauth